#! /usr/local/bin/ruby

require 'rubygems'
require 'bundler/setup'

require 'mage-hand'
include MageHand

require 'lib/configuration'
require 'lib/authorize'
require 'lib/publish'

include Chronicler

# Load in stored options and parse command line
Configuration.init

self.send(Configuration.requested_command)

puts "Done." if Configuration.verbose
